# Generated by Django 6.0 on 2026-01-17 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_resumeprocessing_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationUiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('visible_to_roles', models.JSONField(default=list, help_text='List of roles that can see this navigation group')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation UI Group',
                'verbose_name_plural': 'Navigation UI Groups',
                'db_table': 'navigation_ui_group',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationUiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_name', models.CharField(help_text='Django URL name', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('badge_text', models.CharField(blank=True, help_text="Badge text (e.g., 'New', '5')", max_length=20, null=True)),
                ('badge_class', models.CharField(blank=True, default='badge-primary', help_text='Bootstrap badge class', max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('visible_to_roles', models.JSONField(default=list, help_text='List of roles that can see this item')),
                ('requires_permission', models.CharField(blank=True, help_text='Required permission to view this item', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App.navigationuigroup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='App.navigationuiitem')),
            ],
            options={
                'verbose_name': 'Navigation UI Item',
                'verbose_name_plural': 'Navigation UI Items',
                'db_table': 'navigation_ui_items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
