"""
Django settings for Jobstock project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-r^h6u@l6(ow$0oh5#wd1n@9aulsdg2!!+#x_1hgsg53yg_rvj@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "drf_yasg",
    "App",
    "zoho_integration",
    "django_celery_results",
    "django_celery_beat",
    "App.settings",
    "admin_req",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "App.middleware.ErrorLoggingMiddleware",  # Custom error logging middleware
    "corsheaders.middleware.CorsMiddleware",  # Add this at the top, before CommonMiddleware
    #restapi_error_middleware.RestApiErrorMiddleware",  # Custom REST API error handling middleware
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


ROOT_URLCONF = "Jobstock.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            'builtins': [
                'django.templatetags.static',   # this one loads {% static %} everywhere
            ],
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Navigation context processor (NEW - Reusable for all user groups)
                "App.context_processors_navigation.navigation_context",
                # Add your custom context processors here
                "App.context_processors.global_ctrs",
                "App.context_processors.global_companies",
                "App.context_processors.global_jobs",
                "App.context_processors.global_categories",
                "App.context_processors.global_reviews",
                "App.context_processors.global_companies2",
                "App.context_processors.global_jobs2",
                "App.context_processors.global_needs",
                "App.context_processors.global_explores",
                "App.context_processors.global_candidates",
                "App.context_processors.global_jobs3",
                "App.context_processors.global_employers",
                "App.context_processors.global_jobs4",
                "App.context_processors.global_blogs",
                "App.context_processors.global_categories2",
                "App.context_processors.global_ctrs2",
                "App.context_processors.global_clients",
                "App.context_processors.global_tablists",
                "App.context_processors.global_jobs5",
                "App.context_processors.global_jobs6",
                "App.context_processors.global_jobs7",
                "App.context_processors.global_jobs8",
                "App.context_processors.global_jobs9",
                "App.context_processors.global_jobs10",
                "App.context_processors.global_informations",
                "App.context_processors.global_jobs11",
                "App.context_processors.global_jobs12",
                "App.context_processors.global_ctrs3",
                "App.context_processors.global_jobs13",
                "App.context_processors.global_jobs14",
                "App.context_processors.global_employers2",
                "App.context_processors.global_awards",
                "App.context_processors.global_views",
                "App.context_processors.global_ctrs4",
                "App.context_processors.global_posteds",
                "App.context_processors.global_tables",
                "App.context_processors.global_teams",
                "App.context_processors.global_contacts",
                "App.context_processors.global_buttons",
                "App.context_processors.global_alerts",
                "App.context_processors.global_links",
                "App.context_processors.global_badges",
                "App.context_processors.global_avatars",
                "App.context_processors.global_infos",
                "App.context_processors.global_sliders",
                "App.context_processors.rpo_admin_flag",
            ],
        },
    },
]

WSGI_APPLICATION = "Jobstock.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Added Manualy
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'data')

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# JAZZMIN_SETTINGS = {
#     # 🎯 Branding
#     "site_title": "AI CRM Admin",
#     "site_header": "AI CRM",
#     "site_brand": "AI CRM",
#     "site_logo": "img/logo.png",
#     "site_logo_classes": "img-circle",
#     "site_icon": "img/favicon.ico",   # favicon
#     "welcome_sign": "Welcome to AI CRM Admin",
#     "copyright": "AI CRM Ltd",

#     # 🌙 UI
#     "theme": "darkly",
#     "show_sidebar": True,
#     "navigation_expanded": True,

#     # 🔍 Search
#     "search_model": ["auth.User", "crm.Customer"],

#     # 📌 Top Menu
#     "topmenu_links": [
#         {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
#         {"model": "auth.User"},
#         {"app": "crm"},
#     ],

#     # 📂 Sidebar Menu Control
#     "order_with_respect_to": [
#         "auth",
#         "crm",
#         "sales",
#     ],

#     "hide_apps": ["sessions"],
#     "hide_models": ["auth.Group"],

#     # 🧩 Icons
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "crm.customer": "fas fa-address-book",
#         "sales.order": "fas fa-shopping-cart",
#     },

#     # 🚀 Custom Links
#     "custom_links": {
#         "crm": [{
#             "name": "Reports",
#             "url": "/admin/crm/reports/",
#             "icon": "fas fa-chart-line",
#             "permissions": ["crm.view_customer"],
#         }]
#     },

#     # 🔐 User menu
#     "usermenu_links": [
#         {"name": "Change Password", "url": "admin:password_change"},
#         {"name": "Logout", "url": "admin:logout"},
#     ],
# }

# JAZZMIN_UI_TWEAKS = {
#     "theme": "darkly",
#     "navbar_fixed": True,
#     "sidebar_fixed": True,
#     "footer_fixed": False,
#     "sidebar_nav_child_indent": True,
#     "sidebar_nav_compact_style": False,
# }



JAZZMIN_SETTINGS = {
    "site_title": "My Admin",
    "site_header": "My Admin Panel",
    "site_brand": "MyApp",
    "welcome_sign": "Welcome to MyApp Admin",
    "search_model": ["auth.User"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "theme": "darkly",  # dark mode
}
# JAZZMIN_UI_TWEAKS = {
#     "theme": "darkly",
#     "navbar_small_text": False,
#     "sidebar_small_text": False,
#     "brand_small_text": False,
#     "sidebar_nav_child_indent": True,
# }


# ============================================
# CELERY CONFIGURATION
# ============================================
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_RESULT_EXTENDED = True

# Celery Beat Schedule (for periodic tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# ============================================
# DOCUMENT PROCESSING CONFIGURATION
# ============================================
# Directory for temporary document processing
DOCUMENT_PROCESSING_DIR = os.path.join(BASE_DIR, 'temp_processing')
if not os.path.exists(DOCUMENT_PROCESSING_DIR):
    os.makedirs(DOCUMENT_PROCESSING_DIR)

# SpaCy model to use
SPACY_MODEL = 'en_core_web_sm'  # You'll need to download this: python -m spacy download en_core_web_sm

# Transformers model for document understanding
TRANSFORMERS_MODEL = 'microsoft/layoutlm-base-uncased'

# LayoutParser configuration
LAYOUTPARSER_MODEL = 'lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config'


# ============================================
# LOGGING CONFIGURATION
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'App': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ============================================================================
# Django REST Framework Configuration
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'rest_framework.authentication.SessionAuthentication',
    #     'rest_framework.authentication.BasicAuthentication',
    # ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    # ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'EXCEPTION_HANDLER': 'App.utils.drf_exception_handler.custom_exception_handler'
    #'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    #'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

# Swagger/OpenAPI Documentation Settings
# SWAGGER_SETTINGS = {
#     'SECURITY_DEFINITIONS': {
#         'Basic': {
#             'type': 'basic'
#         },
#         'Session': {
#             'type': 'apiKey',
#             'name': 'sessionid',
#             'in': 'cookie'
#         }
#     },
#     'USE_SESSION_AUTH': True,
#     'JSON_EDITOR': True,
#     'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
# }
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer <token>"',
        },
        # ... other definitions ...
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    '*',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
