# Generated by Django 6.0 on 2026-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ResponseBody',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
